language: go
install: true
sudo: required
addons:
  apt:
    packages:
    - docker-ce
go:
- "1.10.x"
jobs:
  fast_finish: true
  include:
  - script: make test
  - stage: lint
    script:
    - while true; do echo .; sleep 30; done & make lint || true
  - stage: push to docker
    script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - if [ -n "$TRAVIS_TAG" ]; then make TAG=$TRAVIS_TAG push; else make push; fi
env:
  global:
  - secure: "SjrMAEH9FiPxMfveSUZDxNYPZV/e2jADzMyrUi1IUY2c5osoDfUMR/cXBoLQdY1v0eFnE9lnZyfp1oCTNOVB+WU+5okl7rzB0fAEEpKtbhlacoF8UCr82JRpQ1neGoESd0zpzsfeVYeMGaQcn2+HwVBeMDn2JGu00bS2N+dF5LOlV1juWy4EueZNHLu2heypjg6Zo0o1Txd1gTdsNgt8UGwytVT2yNwIb7ZED2shJ4E6kJL11ktwNOE+4LlvjHnTISRPXGN9ZfaeeRk2tOuKaXQrQz+UcHOsDK//5Hh/6nvld0zkfg5uLrxDNH2B++oPPov9uU6iBmWuRSVWvb2ril7/NWJappFe6n8njJVKUqSKaWMh2r/0LhYkohYWCk2UZBZwsVRRZRWHPHlBs95zLAuPc5YXmwnfR3Goc47dRebLtRCmhRIV3I8V2awB0DmC6gPWWtgY7NCfz6dbtxRBTEdKPVB1kTqMBD1lF3IGIOAZfJXNVb3nhPg7ymF6OqUWFylxzDyFrd/+gROanR2R6lUZfebYQIVxKirA+1hxjGDcQxQt4ixx1VhG5B7ELMFxE8gE5N6GX6tVd074OJ2SFwtukD+kxpGOQKfG8QVvQVf18c2VIDfy6aawE6sBP2PkSlA4+KVOiH9tVoI2EOzwgxP8zONFOXskQ8or2E083wg="
  - secure: "FZyoC7kCrVrFq9ju88pFhwmzLaIEx/eNFONOnYwfP9cWg08C9q3hd80mo+PQFQQdjndsZa0SM154Y6HTZ1UGW20wqEUpCZA/wV2hRInbIZHXR0MD8Evp0BeF1AM+53nKKfVpTH4+JoU4jtMZnb/TUi2+1UvfKJjgMAmEVe6qGnZme7tJIA064+n7+CKjsTf3aPtap+aWBWt+Dk6Xo0BbbjNwr70D4Id7tb7ijm6GfRgkdT/7Tj7ItyGjq+8z9ub1jQpnt50PYHJjjp03wssYOH8EhFKGJ8cJRMRBiWYsllMMtIIfpVApTgU8PlWI04Jo+K6kLK6mxeRKYu/efoRW21H97d5Wxk76Ziw2dsnFcCLJs6OrexCHhcQdqsZhl9WoRE40SiUK36a/vaOVKLZ3h/T/sNYnovCzzYVXheCXuyXPjxEXhsPQVuhgYEUTggpzLZv9cRuNMbiawil2KLVvYlPnIC6nBsih5zDhVkMxzzfxNe+0+RXE5stjovMPC6ZB1yDftHRz18/1ASOqYDO8l7mGaW4C2w2MDwZT1Isx7NK5+mO1LEf90E9WXWkiagWQ+SiZ2gmLGz4NPF4iUZVUR64b55GnO9UC1TBrY7pnG3EKPENYFCKwf7FTKLqRZz8NvlLByLNieC3vCfMN3seZJgYWQBWi+V3kfNKuYEVvnlg="
notifications:
  slack:
    rooms:
      secure: "nT5C9IdGO9VYu3+OCclsGVBuKajxAztObHt5e9Pn2eVHwBY1Dgq8Y2HvwBJz2dVqkTwwY4ZRjYAXLB87U8LG+rJMOi+sT1V2o+A6yNzAAJ9BEr50vbPrDAmxERNljYfIMGPgFkYa5Wl7GsIndz25lXUqWDMPupcQostkiGr8HjbKJUWz2MGo/SFg8X3VPfx1e6cFs9HzLemfON96P1LSEKy2xlch+pfOqA3gcF1Gf+Rtuvud3KSaQWBDb51TvEtI7eqrpGRHkpXi8IJ5tFEwzVQVdAnmlooqm708yP94HiwmGww6HhHvirijEEbzutGmJMAO+TtNx9r9st89KgPZ8bJjk0jjNIgAVCoFlvKccSMtd65w72WQ1DckaszSBWAVaT5YCv/uh/HJ0axWmfLnhmzkUsLHvYIgihWLdRwGu050iFeGopMalGnUmkzNQpbVm5wCsVBWkOK8xsX2AkEFf+wIAhoC/6x+gZu9R4YPKahHsAcSX/iXyi/G4IV/6sFc2cAl9dIRxwgik1KM/ghPhXR8fdK9T4+b3Z3mJz4EYEDYP4VNheKrpmgug1gJOvmzjdLhu+i0Fnse09Dr8t/4XyIVeTwJ+bOE2eF2lD/SB0c7daM9ARgG2C+Zhudj7dW56gLOna1BoOxDQ1/SELdX5r6qIsQ/bUv8dx3mjA5cU3Q="
