apiVersion: v1
kind: ServiceAccount
metadata:
  name: remesher
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: remesher
  labels:
    app: remesher
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: remesher
    spec:
      serviceAccountName: remesher
      containers:
        - image: tsuru/remesher
          imagePullPolicy: Always
          name: remesher
          command: ["./remesher"]
          args:
            - --neighborhood-label
            - "tsuru.io/pool"
            - --num-workers
            - "2"
            - --log-level
            - info
          env:
            # Use Kubernetes API as the calico backing datastore.
            - name: DATASTORE_TYPE
              value: "kubernetes"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: remesher
rules:
  - apiGroups: [""]
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["crd.projectcalico.org"]
    resources:
      - bgppeers
    verbs:
      - create
      - get
      - list
      - update
      - watch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: remesher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: remesher
subjects:
- kind: ServiceAccount
  name: remesher
  namespace: kube-system
